services:
  - type: web
    name: garcom-virtual-sabor-da-casa
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/status
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
